### ISSUE TITLE
Some point need to be noticed for the users like me

### ISSUE THREAD

**Issue by wushyer** [PavriLab/hicer-nf#1]
1. specify the absolute path for the fastq files
2. modify the resource config according to your system
3. samples.txt files need to be TAB-separated with absolute path
4. resolution should be checked with no redundant in the command (not same with default)
5. recommend singularity or docker to launch

Thank you for all the developers debugging to make it smoothly!

Best
Shuangyang

**Comment by dmalzl** [comment]
Dear Shuangyang,

Thanks again for pointing out these shortcomings. I have updated the README.md file to point out these things for future users. Please have a look at it and tell me if you feel like missing anything.

In addition, I also took care of the resolution duplication, where the pipeline now removed duplicates from the resolutions list.

Best regards,
Daniel
